version: '2'
services:
  phabricator:
    build:
      dockerfile: . 
      context: .
    container_name: phab_prod
    expose:
     - "8080"
    ports:
      - "222:222"
      - "8080:8080"
    volumes:
      - datavolume_app:/var/www/html:rw
    stdin_open: true
    tty: true

   
  db:
    container_name: phabricator_mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: phabrictor
      MYSQL_DATABASE: phabricator
    ports:
      - "3017:3017"
    stdin_open: true
    tty: true
    


