version: "2"
services:
  phpconfiguration:
    image: php:7.0
    container_name: php
    build:
      dockerfile: Dockerfile
      context: .
    working_dir: /var/www/html 
    volumes:
      - /var/www/html:/var/www/html:rw
    ports:
      - "3600:80"
    stdin_open: true
    tty: true

